fixes error when pkgConfig is passed
This erorr is quite confusing because it points to the name attribute of
the derivation:

    error: cannot coerce a set to a string, at /nix/store/fnvlra5mvqyk67id2q4plavmq399cx9g-yarn2nix-71dc877a79a6a49f1c3a49efc2480095639248d6-src/default.nix:119:7

Because pkgConfig is a set it can't be turned into a string as all the
derivation arguments get transformed into environment variables for the
builder.